language: php

sudo: false

addons:
  firefox: "47.0.1"
  postgresql: "9.6"

services:
  mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
- 7.0
- 7.1
- 7.2
- 7.3
- 7.4

env:
- MOODLE_BRANCH=master           DB=pgsql
- MOODLE_BRANCH=master           DB=mysqli
- MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
- MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
- MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli

matrix:
  exclude:
  - php: 7.4
    env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
  - php: 7.4
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
  - php: 7.3
    env: MOODLE_BRANCH=master           DB=mysqli
  - php: 7.3
    env: MOODLE_BRANCH=master           DB=pgsql
  - php: 7.3
    env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
  - php: 7.3
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
  - php: 7.1
    env: MOODLE_BRANCH=master           DB=mysqli
  - php: 7.1
    env: MOODLE_BRANCH=master           DB=pgsql
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
  - php: 7.0
    env: MOODLE_BRANCH=master           DB=mysqli
  - php: 7.0
    env: MOODLE_BRANCH=master           DB=pgsql
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14
  - nvm use 14
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
